### ISSUE TITLE
Declarative dependency management

### ISSUE THREAD

**Issue by vigoo** [golemcloud/wasm-rpc#81]
For setting up worker to worker communication, the stub generator should support declarative configuration which defines which (language-independent) sub projects are supposed to be able to call each other.

With this declarative information, the stub generator's procedural steps can be ran automated as a series of generating and building stubs, adding stubs as dependencies and in the and composing various wasms.

Note that we cannot fully automate this because we don't have a way to build the user's components (as they can use any language and tooling). We can still point to the build output in the declarative configuration and expose the declarative mode as a two-phase (pre-build and post-build commands). 

The cargo-make support can also build on this new feature, simplifying the generated makefile and making it easier to change the project relationships through the declarative w2w specification when working with rust.

Part of implementing the new feature must be to
- cover it with tests
- including tests for circular and self-references

**Comment by noise64** [comment]
Will be continued in:
 - https://github.com/golemcloud/wasm-rpc/issues/88
 -
